# Generated by Django 4.2 on 2023-05-04 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_user_first_name_remove_user_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
